/**
 * University picker dataset (QS-style world list + full Lebanese coverage),
 * sourced from the product team's curated list. Entries are [name, ISO-3166
 * alpha-2 country]. The picker treats this as suggestions only — education
 * entries remain free text so no institution is ever unrepresentable.
 *
 * Loaded lazily (dynamic import) so it never weighs on the initial bundle.
 */
export type UniversityTuple = readonly [name: string, country: string];

export const UNIVERSITIES: readonly UniversityTuple[] = [
  ["Massachusetts Institute of Technology (MIT)", "US"],
  ["Imperial College London", "GB"],
  ["Stanford University", "US"],
  ["University of Oxford", "GB"],
  ["Harvard University", "US"],
  ["University of Cambridge", "GB"],
  ["California Institute of Technology (Caltech)", "US"],
  ["ETH Zurich", "CH"],
  ["UCL", "GB"],
  ["National University of Singapore (NUS)", "SG"],
  ["The University of Hong Kong", "HK"],
  ["Nanyang Technological University, Singapore (NTU Singapore)", "SG"],
  ["Peking University", "CN"],
  ["Tsinghua University", "CN"],
  ["University of Pennsylvania", "US"],
  ["Cornell University", "US"],
  ["Yale University", "US"],
  ["The Chinese University of Hong Kong (CUHK)", "HK"],
  ["The University of New South Wales (UNSW Sydney)", "AU"],
  ["Johns Hopkins University", "US"],
  ["University of California, Berkeley (UCB)", "US"],
  ["EPFL – École polytechnique fédérale de Lausanne", "CH"],
  ["The University of Melbourne", "AU"],
  ["University of Chicago", "US"],
  ["Technical University of Munich", "DE"],
  ["Fudan University", "CN"],
  ["Princeton University", "US"],
  ["The University of Sydney", "AU"],
  ["Australian National University (ANU)", "AU"],
  ["McGill University", "CA"],
  ["Monash University", "AU"],
  ["University of Toronto", "CA"],
  ["The Hong Kong University of Science and Technology", "HK"],
  ["Université PSL", "FR"],
  ["The University of Edinburgh", "GB"],
  ["Shanghai Jiao Tong University", "CN"],
  ["King's College London", "GB"],
  ["Seoul National University", "KR"],
  ["The University of Tokyo", "JP"],
  ["The University of Manchester", "GB"],
  ["The University of Queensland", "AU"],
  ["Yonsei University", "KR"],
  ["Columbia University", "US"],
  ["Institut Polytechnique de Paris", "FR"],
  ["Northwestern University", "US"],
  ["University of British Columbia", "CA"],
  ["Zhejiang University", "CN"],
  ["Delft University of Technology", "NL"],
  ["University of California, Los Angeles (UCLA)", "US"],
  ["The Hong Kong Polytechnic University", "HK"],
  ["University of Michigan-Ann Arbor", "US"],
  ["City University of Hong Kong (CityUHK)", "HK"],
  ["Korea University", "KR"],
  ["National Taiwan University (NTU)", "TW"],
  ["Carnegie Mellon University", "US"],
  ["Universiti Malaya (UM)", "MY"],
  ["University of Bristol", "GB"],
  ["New York University (NYU)", "US"],
  ["KU Leuven", "BE"],
  ["University of Amsterdam", "NL"],
  ["Ludwig-Maximilians-Universität München", "DE"],
  ["The London School of Economics and Political Science (LSE)", "GB"],
  ["KFUPM", "SA"],
  ["Kyoto University", "JP"],
  ["KAIST", "KR"],
  ["Brown University", "US"],
  ["The University of Auckland", "NZ"],
  ["The University of Warwick", "GB"],
  ["University of Birmingham", "GB"],
  ["Duke University", "US"],
  ["Lund University", "SE"],
  ["University of Texas at Austin", "US"],
  ["Sorbonne University", "FR"],
  ["University of Illinois Urbana-Champaign", "US"],
  ["Trinity College Dublin, The University of Dublin", "IE"],
  ["Université Paris-Saclay", "FR"],
  ["The University of Western Australia", "AU"],
  ["University of Leeds", "GB"],
  ["Adelaide University", "AU"],
  ["University of Glasgow", "GB"],
  ["University of California, San Diego (UCSD)", "US"],
  ["KTH Royal Institute of Technology", "SE"],
  ["The University of Sheffield", "GB"],
  ["Universidad de Buenos Aires (UBA)", "AR"],
  ["Durham University", "GB"],
  ["Universität Heidelberg", "DE"],
  ["Politecnico di Milano", "IT"],
  ["University of Technology Sydney", "AU"],
  ["Uppsala University", "SE"],
  ["Nanjing University", "CN"],
  ["University of Copenhagen", "DK"],
  ["Pennsylvania State University", "US"],
  ["University of Washington", "US"],
  ["Boston University", "US"],
  ["The University of Osaka", "JP"],
  ["University of Alberta", "CA"],
  ["Institute of Science Tokyo", "JP"],
  ["University of Nottingham", "GB"],
  ["Freie Universitaet Berlin", "DE"],
  ["University of Zurich", "CH"],
  ["Purdue University", "US"],
  ["University College Dublin", "IE"],
  ["Tohoku University", "JP"],
  ["Queen Mary University of London", "GB"],
  ["RWTH Aachen University", "DE"],
  ["Technical University of Denmark", "DK"],
  ["Pohang University of Science And Technology (POSTECH)", "KR"],
  ["King Saud University", "SA"],
  ["Sungkyunkwan University (SKKU)", "KR"],
  ["Qatar University", "QA"],
  ["KIT, Karlsruhe Institute of Technology", "DE"],
  ["Sapienza University of Rome", "IT"],
  ["University of Southampton", "GB"],
  ["University of Waterloo", "CA"],
  ["Utrecht University", "NL"],
  ["Lomonosov Moscow State University", "RU"],
  ["University of St Andrews", "GB"],
  ["Indian Institute of Technology Delhi (IITD)", "IN"],
  ["Leiden University", "NL"],
  ["Pontificia Universidad Católica de Chile (UC)", "CL"],
  ["RMIT University", "AU"],
  ["Rice University", "US"],
  ["Alma Mater Studiorum - Università di Bologna", "IT"],
  ["University of Helsinki", "FI"],
  ["University of Bath", "GB"],
  ["Aalto University", "FI"],
  ["Macquarie University (Sydney, Australia)", "AU"],
  ["Aarhus University", "DK"],
  ["Universiti Sains Malaysia (USM)", "MY"],
  ["Universiti Kebangsaan Malaysia (UKM)", "MY"],
  ["University of Oslo", "NO"],
  ["University of Wisconsin-Madison", "US"],
  ["Universidade de São Paulo", "BR"],
  ["Indian Institute of Technology Bombay (IITB)", "IN"],
  ["University of Science and Technology of China", "CN"],
  ["University of Exeter", "GB"],
  ["University of California, Davis", "US"],
  ["Universiti Putra Malaysia (UPM)", "MY"],
  ["University of Liverpool", "GB"],
  ["Humboldt-Universität zu Berlin", "DE"],
  ["University of Vienna", "AT"],
  ["Georgia Institute of Technology", "US"],
  ["National Tsing Hua University - NTHU", "TW"],
  ["Western University", "CA"],
  ["Universidad Nacional Autónoma de México  (UNAM)", "MX"],
  ["Tongji University", "CN"],
  ["Khalifa University", "AE"],
  ["Erasmus University Rotterdam", "NL"],
  ["Newcastle University", "GB"],
  ["Ghent University", "BE"],
  ["University of Basel", "CH"],
  ["Eindhoven University of Technology", "NL"],
  ["University of Southern California", "US"],
  ["Wageningen University & Research", "NL"],
  ["Hanyang University", "KR"],
  ["Nagoya University", "JP"],
  ["University of Groningen", "NL"],
  ["Technische Universität Berlin (TU Berlin)", "DE"],
  ["Universiti Teknologi Malaysia", "MY"],
  ["University of North Carolina at Chapel Hill", "US"],
  ["University of York", "GB"],
  ["Université de Montréal", "CA"],
  ["Washington University in St. Louis", "US"],
  ["Lancaster University", "GB"],
  ["Universitat de Barcelona", "ES"],
  ["Wuhan University", "CN"],
  ["Stockholm University", "SE"],
  ["University of Geneva", "CH"],
  ["Texas A&M University", "US"],
  ["Indian Institute of Technology Madras (IITM)", "IN"],
  ["Kyushu University", "JP"],
  ["Arizona State University", "US"],
  ["University of California, Santa Barbara (UCSB)", "US"],
  ["Chalmers University of Technology", "SE"],
  ["McMaster University", "CA"],
  ["Queen's University Belfast", "GB"],
  ["Al-Farabi Kazakh National University", "KZ"],
  ["National Yang Ming Chiao Tung University (NYCU Taiwan)", "TW"],
  ["Cardiff University", "GB"],
  ["Hokkaido University", "JP"],
  ["Queen's University at Kingston", "CA"],
  ["Michigan State University", "US"],
  ["Emory University", "US"],
  ["University of Cape Town", "ZA"],
  ["Technische Universität Dresden", "DE"],
  ["Universidad de Chile", "CL"],
  ["Vrije Universiteit Amsterdam", "NL"],
  ["Tecnológico de Monterrey", "MX"],
  ["Curtin University", "AU"],
  ["Harbin Institute of Technology", "CN"],
  ["National Cheng Kung University (NCKU)", "TW"],
  ["Technische Universität Wien", "AT"],
  ["Universitas Indonesia", "ID"],
  ["University of Bern", "CH"],
  ["University of Wollongong", "AU"],
  ["Université catholique de Louvain (UCLouvain)", "BE"],
  ["University of Reading", "GB"],
  ["University of Otago", "NZ"],
  ["Complutense University of Madrid", "ES"],
  ["King Abdulaziz University (KAU)", "SA"],
  ["The Ohio State University", "US"],
  ["Waseda University", "JP"],
  ["Loughborough University", "GB"],
  ["Università di Padova", "IT"],
  ["Indian Institute of Technology Kharagpur (IIT-KGP)", "IN"],
  ["Gadjah Mada University", "ID"],
  ["Politecnico di Torino", "IT"],
  ["Tel Aviv University", "IL"],
  ["Rheinische Friedrich-Wilhelms-Universität Bonn", "DE"],
  ["Universität Hamburg", "DE"],
  ["Universitat Autònoma de Barcelona", "ES"],
  ["Chulalongkorn University", "TH"],
  ["Hamad Bin Khalifa University (HBKU)", "QA"],
  ["Keio University", "JP"],
  ["Massey University", "NZ"],
  ["Hong Kong Baptist University", "HK"],
  ["United Arab Emirates University", "AE"],
  ["Friedrich-Alexander-Universität Erlangen-Nürnberg", "DE"],
  ["The Hebrew University of Jerusalem", "IL"],
  ["University College Cork", "IE"],
  ["Indian Institute of Science (IISc) Bangalore", "IN"],
  ["Indian Institute of Technology Kanpur (IITK)", "IN"],
  ["American University of Beirut (AUB)", "LB"],
  ["University of Twente", "NL"],
  ["University of Gothenburg", "SE"],
  ["Universidad Autónoma de Madrid", "ES"],
  ["Deakin University", "AU"],
  ["University of Florida", "US"],
  ["University of Ottawa", "CA"],
  ["Eberhard Karls Universität Tübingen", "DE"],
  ["Griffith University", "AU"],
  ["University of Strathclyde", "GB"],
  ["Universidad de los Andes", "CO"],
  ["University of Lausanne", "CH"],
  ["École Normale Supérieure de Lyon", "FR"],
  ["Tianjin University", "CN"],
  ["Beijing Normal University", "CN"],
  ["University of Lisbon", "PT"],
  ["Central European University", "AT"],
  ["Queensland University of Technology (QUT)", "AU"],
  ["La Trobe University", "AU"],
  ["Victoria University of Wellington", "NZ"],
  ["Beijing Institute of Technology", "CN"],
  ["The University of Newcastle, Australia (UON)", "AU"],
  ["Albert-Ludwigs-Universitaet Freiburg", "DE"],
  ["Université Paris 1 Panthéon-Sorbonne", "FR"],
  ["University of Surrey", "GB"],
  ["Universite libre de Bruxelles", "BE"],
  ["University of Calgary", "CA"],
  ["Technical University of Darmstadt", "DE"],
  ["University of Rochester", "US"],
  ["University of California, Irvine", "US"],
  ["University of Maryland, College Park", "US"],
  ["Maastricht University", "NL"],
  ["University of Minnesota (System)", "US"],
  ["University of Porto", "PT"],
  ["University of Canterbury | Te Whare Wānanga o Waitaha", "NZ"],
  ["American University of Sharjah", "AE"],
  ["Sun Yat-sen University", "CN"],
  ["University of Massachusetts Amherst", "US"],
  ["Universiti Teknologi PETRONAS (UTP)", "MY"],
  ["University of Göttingen", "DE"],
  ["Universitat Pompeu Fabra (Barcelona)", "ES"],
  ["Norwegian University of Science And Technology", "NO"],
  ["Vanderbilt University", "US"],
  ["Singapore University of Technology and Design", "SG"],
  ["University of Macau", "MO"],
  ["University of Virginia", "US"],
  ["University of Cologne", "DE"],
  ["Dartmouth College", "US"],
  ["University of Milan", "IT"],
  ["Taylor's University", "MY"],
  ["Charles University", "CZ"],
  ["University of Sussex", "GB"],
  ["University of Galway", "IE"],
  ["Universitas Airlangga", "ID"],
  ["Universidade Estadual de Campinas (Unicamp)", "BR"],
  ["University of Antwerp", "BE"],
  ["Istanbul Technical University", "TR"],
  ["University of Navarra", "ES"],
  ["University of Pittsburgh", "US"],
  ["UCSI University", "MY"],
  ["Radboud University", "NL"],
  ["University of Bergen", "NO"],
  ["University of Sharjah", "AE"],
  ["University of Southern Denmark (SDU)", "DK"],
  ["Institut Teknologi Bandung (ITB)", "ID"],
  ["University of Aberdeen", "GB"],
  ["Georgetown University", "US"],
  ["University of Warsaw", "PL"],
  ["Swinburne University of Technology", "AU"],
  ["University of Johannesburg", "ZA"],
  ["Universidad Nacional de Colombia", "CO"],
  ["University of Waikato", "NZ"],
  ["Vrije Universiteit Brussel (VUB)", "BE"],
  ["Stellenbosch University", "ZA"],
  ["Xi’an Jiaotong University", "CN"],
  ["Dalhousie University", "CA"],
  ["Ulsan National Institute of Science and Technology (UNIST)", "KR"],
  ["Sichuan University", "CN"],
  ["University of Notre Dame", "US"],
  ["University of Witwatersrand", "ZA"],
  ["Université Paris Cité", "FR"],
  ["Xiamen University", "CN"],
  ["Middle East Technical University", "TR"],
  ["Sultan Qaboos University", "OM"],
  ["Huazhong University of Science and Technology", "CN"],
  ["Linköping University", "SE"],
  ["Kyung Hee University", "KR"],
  ["Shandong University", "CN"],
  ["University of Tasmania", "AU"],
  ["Simon Fraser University", "CA"],
  ["The University of Arizona", "US"],
  ["Rutgers University–New Brunswick", "US"],
  ["Universidad Carlos III de Madrid (UC3M)", "ES"],
  ["University of Leicester", "GB"],
  ["Southern University of Science and Technology (SUSTech)", "CN"],
  ["Bauman Moscow State Technical University", "RU"],
  ["Universität Stuttgart", "DE"],
  ["North Carolina State University", "US"],
  ["University of Colorado Boulder", "US"],
  ["Swansea University", "GB"],
  ["University of Delhi", "IN"],
  ["York University", "CA"],
  ["Heriot-Watt University", "GB"],
  ["Case Western Reserve University", "US"],
  ["University of Jordan", "JO"],
  ["University of Pretoria", "ZA"],
  ["Aalborg University", "DK"],
  ["Jagiellonian University", "PL"],
  ["Koç University", "TR"],
  ["Nankai University", "CN"],
  ["Universität Innsbruck", "AT"],
  ["Technion - Israel Institute of Technology", "IL"],
  ["Indian Institute of Technology Roorkee (IITR)", "IN"],
  ["Southeast University", "CN"],
  ["Universidade Nova de Lisboa", "PT"],
  ["L.N. Gumilyov Eurasian National University (ENU)", "KZ"],
  ["Tufts University", "US"],
  ["University of Miami", "US"],
  ["University of Pisa", "IT"],
  ["South China University of Technology", "CN"],
  ["University of Coimbra", "PT"],
  ["University of Rome \"Tor Vergata\"", "IT"],
  ["Boğaziçi University", "TR"],
  ["Mahidol University", "TH"],
  ["Universiti Brunei Darussalam (UBD)", "BN"],
  ["Abu Dhabi University", "AE"],
  ["Beihang University (former BUAA)", "CN"],
  ["Indian Institute of Technology Guwahati (IITG)", "IN"],
  ["Satbayev University", "KZ"],
  ["University of Tsukuba", "JP"],
  ["Brunel University of London", "GB"],
  ["Birkbeck, University of London", "GB"],
  ["Sciences Po", "FR"],
  ["Sunway University", "MY"],
  ["Pontificia Universidad Catolica del Peru (PUCP)", "PE"],
  ["Sabanci University", "TR"],
  ["RUDN University", "RU"],
  ["Indiana University Bloomington", "US"],
  ["University of Chinese Academy of Sciences (UCAS)", "CN"],
  ["University of Oulu", "FI"],
  ["City St George’s, University of London", "GB"],
  ["Cairo University", "EG"],
  ["Universidad Politécnica de Madrid (UPM)", "ES"],
  ["Université de Liège", "BE"],
  ["Virginia Polytechnic Institute and State University", "US"],
  ["Universidade Federal do Rio de Janeiro", "BR"],
  ["University of Tartu", "EE"],
  ["University of Tehran", "IR"],
  ["University of Illinois Chicago (UIC)", "US"],
  ["University of Münster", "DE"],
  ["University of Victoria (UVic)", "CA"],
  ["Western Sydney University", "AU"],
  ["Flinders University", "AU"],
  ["Goethe-University Frankfurt am Main", "DE"],
  ["University of Luxembourg", "LU"],
  ["National Technical University of Athens", "GR"],
  ["Gwangju Institute of Science and Technology (GIST)", "KR"],
  ["National Taiwan University of Science and Technology (Taiwan Tech)", "TW"],
  ["George Washington University", "US"],
  ["Quaid-i-Azam University", "PK"],
  ["University of East Anglia (UEA)", "GB"],
  ["National University of Sciences & Technology (NUST) Islamabad", "PK"],
  ["Daegu Gyeongbuk Institute of Science and Technology (DGIST)", "KR"],
  ["Northeastern University", "US"],
  ["Université Grenoble Alpes", "FR"],
  ["Università Cattolica del Sacro Cuore", "IT"],
  ["University of Limerick", "IE"],
  ["LUT University", "FI"],
  ["Saint Petersburg State University", "RU"],
  ["Sharif University of Technology", "IR"],
  ["The American University in Cairo", "EG"],
  ["East China Normal University", "CN"],
  ["Pontificia Universidad Javeriana", "CO"],
  ["Università degli Studi di Pavia", "IT"],
  ["Ajman University", "AE"],
  ["Macau University of Science and Technology", "MO"],
  ["Sejong University", "KR"],
  ["University of California, Riverside", "US"],
  ["University of Turku", "FI"],
  ["University of Naples - Federico II", "IT"],
  ["National and Kapodistrian University of Athens", "GR"],
  ["Ruhr-Universität Bochum", "DE"],
  ["University of the Philippines", "PH"],
  ["University of Turin", "IT"],
  ["INTI International University", "MY"],
  ["The Education University of Hong Kong", "HK"],
  ["Dublin City University", "IE"],
  ["Graz University of Technology", "AT"],
  ["University of Florence", "IT"],
  ["Oxford Brookes University", "GB"],
  ["Singapore Management University", "SG"],
  ["University of Saskatchewan", "CA"],
  ["University of Southern Queensland", "AU"],
  ["University of Kent", "GB"],
  ["Aston University", "GB"],
  ["Shenzhen University", "CN"],
  ["University at Buffalo SUNY", "US"],
  ["IPB University (aka Bogor Agricultural University)", "ID"],
  ["Lincoln University", "NZ"],
  ["Prince Mohammad Bin Fahd university", "SA"],
  ["Murdoch University", "AU"],
  ["HSE University", "RU"],
  ["National Taiwan Normal University (NTNU)", "TW"],
  ["Northwestern Polytechnical University", "CN"],
  ["Universität Konstanz", "DE"],
  ["Universität Mannheim", "DE"],
  ["University of Aveiro", "PT"],
  ["Tilburg University", "NL"],
  ["Julius-Maximilians-Universität Würzburg", "DE"],
  ["Auckland University of Technology (AUT)", "NZ"],
  ["Chung-Ang University (CAU)", "KR"],
  ["Czech Technical University in Prague", "CZ"],
  ["Universitat Politècnica de Catalunya · BarcelonaTech (UPC)", "ES"],
  ["Universitat Politecnica de Valencia", "ES"],
  ["Central Queensland University (CQUniversity Australia)", "AU"],
  ["Tampere University", "FI"],
  ["Essex, University of", "GB"],
  ["James Cook University", "AU"],
  ["National Sun Yat-sen University (NSYSU)", "TW"],
  ["Umea University", "SE"],
  ["University of Trento", "IT"],
  ["Aix-Marseille University", "FR"],
  ["Shanghai University", "CN"],
  ["University of Science and Technology Beijing", "CN"],
  ["IE University", "ES"],
  ["University of Dundee", "GB"],
  ["University of Granada", "ES"],
  ["Jordan University of Science & Technology", "JO"],
  ["Pusan National University", "KR"],
  ["Universitat de Valencia", "ES"],
  ["Central South University", "CN"],
  ["Shoolini University of Biotechnology and Management Sciences", "IN"],
  ["Bilkent University", "TR"],
  ["Masaryk University", "CZ"],
  ["Université de Strasbourg", "FR"],
  ["USI - Università della Svizzera italiana", "CH"],
  ["Johannes Kepler University Linz", "AT"],
  ["SOAS University of London", "GB"],
  ["Tashkent Institute of Irrigation and Agricultural Mechanization Engineers - National Research University (TIIAME-NRU)", "UZ"],
  ["University of California, Santa Cruz", "US"],
  ["University of Connecticut", "US"],
  ["Dalian University of Technology", "CN"],
  ["Universidad de Costa Rica", "CR"],
  ["Chongqing University", "CN"],
  ["Università Vita-Salute San Raffaele", "IT"],
  ["Vilnius University", "LT"],
  ["Kazan (Volga region) Federal University", "RU"],
  ["Stony Brook University, State University of New York", "US"],
  ["Anna University", "IN"],
  ["Leibniz University Hannover", "DE"],
  ["University of Bayreuth", "DE"],
  ["Université de Montpellier", "FR"],
  ["Imam Abdulrahman Bin Faisal University (IAU)", "SA"],
  ["Universidad Nacional de La Plata (UNLP)", "AR"],
  ["Universitat Ramon Llull", "ES"],
  ["China Agricultural University", "CN"],
  ["Hunan University", "CN"],
  ["Lebanese American University", "LB"],
  ["University of Canberra", "AU"],
  ["Hiroshima University", "JP"],
  ["Kyungpook National University", "KR"],
  ["Amirkabir University of Technology", "IR"],
  ["Jinan University (China)", "CN"],
  ["Royal Holloway, University of London", "GB"],
  ["Universidad de Sevilla", "ES"],
  ["University of Bordeaux", "FR"],
  ["Ewha Womans University", "KR"],
  ["Jilin University", "CN"],
  ["Novosibirsk State University", "RU"],
  ["Prince Sultan University", "SA"],
  ["University of Electronic Science and Technology of China", "CN"],
  ["National Taipei University of Technology", "TW"],
  ["Sogang University", "KR"],
  ["Universitas Padjadjaran (UNPAD)", "ID"],
  ["Concordia University", "CA"],
  ["Institut Teknologi Sepuluh Nopember (ITS Surabaya)", "ID"],
  ["University of Bradford", "GB"],
  ["Johannes Gutenberg Universität Mainz", "DE"],
  ["Universität Potsdam", "DE"],
  ["Aristotle University of Thessaloniki", "GR"],
  ["University of Genoa", "IT"],
  ["Duy Tan University", "VN"],
  ["Iran University of Science and Technology", "IR"],
  ["Kobe University", "JP"],
  ["Moscow Institute of Physics and Technology (MIPT / Moscow Phystech)", "RU"],
  ["Ural Federal University - UrFU", "RU"],
  ["Warsaw University of Technology", "PL"],
  ["Indian Institute of Technology BHU Varanasi (IIT BHU Varanasi)", "IN"],
  ["Tomsk State University", "RU"],
  ["Washington State University", "US"],
  ["UNESP", "BR"],
  ["King Khalid University", "SA"],
  ["China Medical University", "TW"],
  ["Conservatoire National des Arts et Métiers (CNAM)", "FR"],
  ["University of Kansas", "US"],
  ["Bond University", "AU"],
  ["Universiti Tenaga Nasional (UNITEN)", "MY"],
  ["Dongguk University", "KR"],
  ["Justus-Liebig-University Giessen", "DE"],
  ["Renmin (People's) University of China", "CN"],
  ["University of Huddersfield", "GB"],
  ["University of Jyväskylä", "FI"],
  ["University of Cyprus (UCY)", "CY"],
  ["Chandigarh University", "IN"],
  ["Université Laval", "CA"],
  ["Asia Pacific University of Technology and Innovation (APU) Malaysia", "MY"],
  ["Northumbria University at Newcastle", "GB"],
  ["Pontificia Universidad Católica Argentina", "AR"],
  ["Universidad Austral", "AR"],
  ["University of Ljubljana", "SI"],
  ["Belarusian State University", "BY"],
  ["Ben-Gurion University of The Negev", "IL"],
  ["University of Utah", "US"],
  ["The University of Georgia", "US"],
  ["Saint Joseph University of Beirut (USJ)", "LB"],
  ["University of Iceland", "IS"],
  ["University of Windsor", "CA"],
  ["Colorado State University", "US"],
  ["Iowa State University", "US"],
  ["Universität  Leipzig", "DE"],
  ["Universiti Utara Malaysia (UUM)", "MY"],
  ["University of Milano-Bicocca", "IT"],
  ["Edith Cowan University", "AU"],
  ["Florida State University", "US"],
  ["Indian Institute of Technology Indore", "IN"],
  ["University of Guelph", "CA"],
  ["Boston College", "US"],
  ["Universiti Teknologi MARA - UiTM", "MY"],
  ["Ain Shams University in Cairo (ASU, Cairo)", "EG"],
  ["Charles Darwin University", "AU"],
  ["Universidad de Santiago de Chile (USACH)", "CL"],
  ["University of Houston", "US"],
  ["Chiang Mai University", "TH"],
  ["Inha University", "KR"],
  ["Jawaharlal Nehru University", "IN"],
  ["Thammasat University", "TH"],
  ["Al Ain University", "AE"],
  ["Pakistan Institute of Engineering and Applied Sciences (PIEAS)", "PK"],
  ["University of Manitoba", "CA"],
  ["University of Salamanca", "ES"],
  ["University of Stirling", "GB"],
  ["Zhejiang University of Technology", "CN"],
  ["Baku State University", "AZ"],
  ["Université Paul Sabatier Toulouse III", "FR"],
  ["Bangor University", "GB"],
  ["King Faisal University", "SA"],
  ["Universität Jena", "DE"],
  ["Ajou University", "KR"],
  ["Hacettepe University", "TR"],
  ["Paris Lodron University of Salzburg", "AT"],
  ["University of Minho", "PT"],
  ["University of Siena", "IT"],
  ["Birla Institute of Technology and Science, Pilani", "IN"],
  ["Colorado School of Mines", "US"],
  ["Hitotsubashi University", "JP"],
  ["Ulm University", "DE"],
  ["University of Delaware", "US"],
  ["University of Hull", "GB"],
  ["Ateneo de Manila University", "PH"],
  ["Coventry University", "GB"],
  ["Lingnan University, Hong Kong", "HK"],
  ["Rensselaer Polytechnic Institute", "US"],
  ["Universität Bremen", "DE"],
  ["University of Brescia", "IT"],
  ["Zhengzhou University", "CN"],
  ["Brno University of Technology", "CZ"],
  ["Indian Institute of Technology Hyderabad (IITH)", "IN"],
  ["Saarland University", "DE"],
  ["Universiti Malaysia Pahang Al-Sultan Abdullah (UMPSA)", "MY"],
  ["University of the Punjab", "PK"],
  ["Zayed University", "AE"],
  ["Technische Universität Bergakademie Freiberg", "DE"],
  ["Eötvös Loránd University", "HU"],
  ["Ulster University", "GB"],
  ["Tulane University", "US"],
  ["University of Iowa", "US"],
  ["Vellore Institute of Technology (VIT), Vellore, India", "IN"],
  ["Ca' Foscari University of Venice", "IT"],
  ["China University of Petroleum, Beijing", "CN"],
  ["Federal University of Minas Gerais (UFMG)", "BR"],
  ["Manchester Metropolitan University", "GB"],
  ["Tallinn University of Technology (TalTech)", "EE"],
  ["University of Debrecen", "HU"],
  ["University of Dhaka", "BD"],
  ["University of Kwazulu-Natal", "ZA"],
  ["American University of Ras Al Khaimah", "AE"],
  ["Free University of Bozen-Bolzano", "IT"],
  ["Lahore University of Management Sciences (LUMS)", "PK"],
  ["Management and Science University", "MY"],
  ["Taipei Medical University (TMU)", "TW"],
  ["National Chengchi University", "TW"],
  ["Université Claude Bernard Lyon 1", "FR"],
  ["Universiti Teknologi Brunei", "BN"],
  ["American University of the Middle East", "KW"],
  ["Canadian University Dubai", "AE"],
  ["Universitas Brawijaya", "ID"],
  ["Peter the Great St. Petersburg Polytechnic University", "RU"],
  ["American University in Dubai", "AE"],
  ["Christian-Albrechts-University zu Kiel", "DE"],
  ["HUFS - Hankuk (Korea) University of Foreign Studies", "KR"],
  ["Illinois Institute of Technology", "US"],
  ["Isfahan University of Technology", "IR"],
  ["Pontifícia Universidade Católica do Rio de Janeiro", "BR"],
  ["Lebanese University", "LB"],
  ["National Research Nuclear University MEPhI (Moscow Engineering Physics Institute)", "RU"],
  ["University of Eastern Finland", "FI"],
  ["Istanbul University", "TR"],
  ["Universidade de Santiago de Compostela", "ES"],
  ["University of Agriculture, Faisalabad", "PK"],
  ["University of Tromsø The Arctic University of Norway", "NO"],
  ["University of Szeged", "HU"],
  ["Abai Kazakh National Pedagogical University (Abai University)", "KZ"],
  ["Azerbaijan State University of Economics (UNEC)", "AZ"],
  ["National Chung Hsing University", "TW"],
  ["Southern Cross University", "AU"],
  ["Yildiz Technical University", "TR"],
  ["COMSATS University Islamabad", "PK"],
  ["Hasselt University", "BE"],
  ["MGIMO University", "RU"],
  ["Nottingham Trent University", "GB"],
  ["Al-Ahliyya Amman University", "JO"],
  ["Comillas Pontifical University", "ES"],
  ["University of Hawaiʻi at Mānoa", "US"],
  ["American University", "US"],
  ["Institut National Polytechnique de Toulouse", "FR"],
  ["Otto-von-Guericke-Universität Magdeburg", "DE"],
  ["Asia University Taiwan", "TW"],
  ["Beijing University of Chemical Technology", "CN"],
  ["University of Crete", "GR"],
  ["The Catholic University of Korea (CUK)", "KR"],
  ["Universidad de la República (Udelar)", "UY"],
  ["University of Chemistry and Technology, Prague", "CZ"],
  ["Applied Science University - Bahrain", "BH"],
  ["Symbiosis International (Deemed University)", "IN"],
  ["Universidad Adolfo Ibáñez", "CL"],
  ["Université de Tunis El Manar", "TN"],
  ["China University of Mining and Technology", "CN"],
  ["Florida International University", "US"],
  ["National Central University", "TW"],
  ["Chang Gung University", "TW"],
  ["Comenius University Bratislava", "SK"],
  ["Diponegoro University", "ID"],
  ["Universidad de Concepción", "CL"],
  ["Universita' Politecnica delle Marche", "IT"],
  ["University of Portsmouth", "GB"],
  ["École Centrale de Lyon", "FR"],
  ["Toronto Metropolitan University (formerly Ryerson University)", "CA"],
  ["Abo Akademi University", "FI"],
  ["Beirut Arab University", "LB"],
  ["East China University of Science and Technology", "CN"],
  ["Lehigh University", "US"],
  ["University of Fribourg", "CH"],
  ["Nanjing University of Science and Technology", "CN"],
  ["Stevens Institute of Technology", "US"],
  ["China University of Geosciences", "CN"],
  ["City University of New York", "US"],
  ["Jeonbuk National University", "KR"],
  ["Prince Sattam Bin Abdulaziz University", "SA"],
  ["University of New Brunswick", "CA"],
  ["University of the Basque Country", "ES"],
  ["Konkuk University", "KR"],
  ["Ritsumeikan University", "JP"],
  ["University of Klagenfurt", "AT"],
  ["Jamia Millia Islamia", "IN"],
  ["Kingston University, London", "GB"],
  ["Université de Lille", "FR"],
  ["University of Tabriz", "IR"],
  ["University of Texas at Dallas", "US"],
  ["Eastern Mediterranean University", "CY"],
  ["Government College University, Faisalabad", "PK"],
  ["International Islamic University Malaysia (IIUM)", "MY"],
  ["TU Dortmund University", "DE"],
  ["University of Plymouth", "GB"],
  ["Karl-Franzens-Universitaet Graz", "AT"],
  ["Kaunas University of Technology", "LT"],
  ["Universität Regensburg", "DE"],
  ["University of Malta", "MT"],
  ["Victoria University", "AU"],
  ["Cyprus University of Technology", "CY"],
  ["Goldsmiths, University of London", "GB"],
  ["Indian Institute of Technology (Indian School of Mines), Dhanbad", "IN"],
  ["Jiangsu University", "CN"],
  ["Lincoln University College", "MY"],
  ["SEGi UNIVERSITY", "MY"],
  ["Thapar Institute of Engineering & Technology", "IN"],
  ["The University of Tennessee, Knoxville", "US"],
  ["Universidad de Zaragoza", "ES"],
  ["Universiti Malaysia Terengganu (UMT)", "MY"],
  ["Ahlia University", "BH"],
  ["Azerbaijan State Oil and Industry University", "AZ"],
  ["Bangladesh University of Engineering and Technology", "BD"],
  ["Bar-Ilan University", "IL"],
  ["Bharathiar University", "IN"],
  ["Oregon State University", "US"],
  ["Palacký University Olomouc", "CZ"],
  ["Soochow University", "CN"],
  ["Universidad Panamericana (UP)", "MX"],
  ["Université Côte d'Azur", "FR"],
  ["University of Nicosia", "CY"],
  ["University of Oregon", "US"],
  ["University of South Carolina", "US"],
  ["Jadavpur University", "IN"],
  ["Kasetsart University", "TH"],
  ["Lanzhou University", "CN"],
  ["Maynooth University", "IE"],
  ["Memorial University of Newfoundland", "CA"],
  ["Nanjing University of Aeronautics and Astronautics", "CN"],
  ["National Institute of Technology, Tiruchirappalli", "IN"],
  ["Plekhanov Russian University of Economics", "RU"],
  ["TUHH Hamburg University of Technology", "DE"],
  ["University of Missouri, Columbia", "US"],
  ["University of Zagreb", "HR"],
  ["Adam Mickiewicz University, Poznań", "PL"],
  ["Ankara Üniversitesi", "TR"],
  ["Beijing Forestry University", "CN"],
  ["Beijing University of Technology", "CN"],
  ["Czech University of Life Sciences in Prague", "CZ"],
  ["Northwest Agriculture and Forestry University", "CN"],
  ["Syracuse University", "US"],
  ["Universidad de Alcalá (Madrid)", "ES"],
  ["Université de Rennes", "FR"],
  ["University of Central Florida", "US"],
  ["Far Eastern Federal University", "RU"],
  ["National Research Tomsk Polytechnic University", "RU"],
  ["New Jersey Institute of Technology (NJIT)", "US"],
  ["Umm Al-Qura University", "SA"],
  ["Universidade Federal do Rio Grande Do Sul", "BR"],
  ["University of Bari", "IT"],
  ["University of Cincinnati", "US"],
  ["Brandeis University", "US"],
  ["Budapest University of Technology and Economics", "HU"],
  ["De La Salle University", "PH"],
  ["Instituto Tecnológico Autónomo de México (ITAM)", "MX"],
  ["Missouri University of Science and Technology", "US"],
  ["O.P. Jindal Global University (JGU)", "IN"],
  ["Riga Technical University", "LV"],
  ["Sofia University \"St. Kliment Ohridski\"", "BG"],
  ["Temple University", "US"],
  ["Vietnam National University, Hanoi", "VN"],
  ["Vytautas Magnus University", "LT"],
  ["AGH University of Krakow", "PL"],
  ["Applied Science Private University - Jordan", "JO"],
  ["Holy Spirit University of Kaslik", "LB"],
  ["Norwegian University of Life Sciences", "NO"],
  ["Texas Tech University", "US"],
  ["University of Messina (UniME)", "IT"],
  ["University of South Florida", "US"],
  ["University of Trieste", "IT"],
  ["UWE Bristol (University of the West of England)", "GB"],
  ["Beijing Jiaotong University", "CN"],
  ["Drexel University", "US"],
  ["Jiangnan University", "CN"],
  ["Multimedia University (MMU)", "MY"],
  ["Universidad San Francisco de Quito USFQ", "EC"],
  ["University of Hohenheim", "DE"],
  ["University of New Mexico", "US"],
  ["University of Oklahoma", "US"],
  ["University of Patras", "GR"],
  ["Auezov South Kazakhstan University (SKU)", "KZ"],
  ["Chonnam National University", "KR"],
  ["German Jordanian University", "JO"],
  ["Hong Kong Metropolitan University", "HK"],
  ["Kazakh National Agrarian Research University (KazNARU)", "KZ"],
  ["Qassim University", "SA"],
  ["Shahid Beheshti University (SBU)", "IR"],
  ["Technische Universität Braunschweig", "DE"],
  ["Universidad de Palermo (UP)", "AR"],
  ["University of Dubai", "AE"],
  ["University of Latvia", "LV"],
  ["Verona University", "IT"],
  ["Imam Mohammad Ibn Saud Islamic University – IMSIU", "SA"],
  ["Lovely Professional University (LPU)", "IN"],
  ["Near East University", "CY"],
  ["Savitribai Phule Pune University", "IN"],
  ["Shiraz University", "IR"],
  ["Taras Shevchenko National University of Kyiv", "UA"],
  ["Technological University Dublin", "IE"],
  ["Universidade Católica Portuguesa", "PT"],
  ["University of Engineering & Technology (UET) Lahore", "PK"],
  ["University of Greenwich", "GB"],
  ["University of Pecs", "HU"],
  ["VILNIUS TECH (Vilnius Gediminas Technical University)", "LT"],
  ["Yeungnam University", "KR"],
  ["Aberystwyth University", "GB"],
  ["Alexandria University", "EG"],
  ["Alfaisal University", "SA"],
  ["American University of Central Asia", "KG"],
  ["Azerbaijan Technical University", "AZ"],
  ["Bournemouth University", "GB"],
  ["Carleton University", "CA"],
  ["Chungnam National University", "KR"],
  ["Edinburgh Napier University", "GB"],
  ["Egypt Japan University of Science & Technology", "EG"],
  ["El Colegio de México, A.C.", "MX"],
  ["Gdańsk University of Technology", "PL"],
  ["Georgia State University", "US"],
  ["ITMO University", "RU"],
  ["Keele University", "GB"],
  ["Khazar University", "AZ"],
  ["Martin-Luther-Universität Halle-Wittenberg", "DE"],
  ["National University of Uzbekistan named after Mirzo Ulugbek", "UZ"],
  ["Ocean University of China", "CN"],
  ["Princess Nourah bint Abdulrahman University", "SA"],
  ["Rutgers University–Newark", "US"],
  ["Saveetha Institute of Medical And Technical Sciences (SIMATS) , Tamil Nadu,India", "IN"],
  ["The National University of Science and Technology MISIS", "RU"],
  ["Ton Duc Thang University", "VN"],
  ["Universidad Católica del Uruguay (UCU)", "UY"],
  ["Universidad Central de Venezuela", "VE"],
  ["Universidad Nacional de Córdoba - UNC", "AR"],
  ["Universidade de Vigo", "ES"],
  ["Universidade Federal de São Paulo", "BR"],
  ["Universität Duisburg-Essen", "DE"],
  ["Université de Lorraine", "FR"],
  ["Universiti Tunku Abdul Rahman (UTAR)", "MY"],
  ["University of Baghdad", "IQ"],
  ["University of Belgrade", "RS"],
  ["University of Bucharest", "RO"],
  ["University of Haifa", "IL"],
  ["University of Maryland, Baltimore", "US"],
  ["University of Maryland, Baltimore County", "US"],
  ["University of Modena and Reggio Emilia", "IT"],
  ["University of Mons", "BE"],
  ["University of Namur", "BE"],
  ["University of Nebraska - Lincoln", "US"],
  ["University of Palermo", "IT"],
  ["Viet Nam National University Ho Chi Minh City (VNU-HCM)", "VN"],
  ["Wake Forest University", "US"],
  ["Wayne State University", "US"],
  ["Auburn University", "US"],
  ["Australian Catholic University", "AU"],
  ["Babes-Bolyai University", "RO"],
  ["Baku Engineering University", "AZ"],
  ["Catania University", "IT"],
  ["Chiba University", "JP"],
  ["De Montfort University", "GB"],
  ["Donghua University", "CN"],
  ["Gebze Technical University (GTU)", "TR"],
  ["Indian Institute of Technology Gandhinagar (IITGN)", "IN"],
  ["Iscte - University Institute of Lisbon", "PT"],
  ["Khoja Akhmet Yassawi International Kazakh-Turkish University", "KZ"],
  ["Kuwait University", "KW"],
  ["Liverpool John Moores University", "GB"],
  ["Manipal Academy of Higher Education, Manipal, Karnataka, India", "IN"],
  ["Montanuniversität Leoben", "AT"],
  ["National Technical University of Ukraine \"Igor Sikorsky Kyiv Polytechnic Institute\"", "UA"],
  ["Pontificia Universidad Católica de Valparaíso", "CL"],
  ["Prince of Songkla University", "TH"],
  ["Sechenov University", "RU"],
  ["Southwest Jiaotong University", "CN"],
  ["Taif University", "SA"],
  ["The New School, New York City and Paris", "US"],
  ["Tokyo University of Science", "JP"],
  ["Universidad de Antioquia", "CO"],
  ["Universidad de La Habana", "CU"],
  ["Universidad de Montevideo (UM)", "UY"],
  ["Universidad Iberoamericana Ciudad de México - IBERO", "MX"],
  ["Universidade de Brasília", "BR"],
  ["Università degli Studi della Tuscia (University of Tuscia)", "IT"],
  ["Università degli studi Roma Tre", "IT"],
  ["Universitas Hasanuddin", "ID"],
  ["Universitat Rovira i Virgili", "ES"],
  ["Universiti Pendidikan Sultan Idris (UPSI)", "MY"],
  ["University of Alicante", "ES"],
  ["University of Calabria", "IT"],
  ["University of Colorado Denver | Anschutz Medical Campus", "US"],
  ["University of Ghana", "GH"],
  ["University of Hertfordshire", "GB"],
  ["University of Hyderabad", "IN"],
  ["University of Lincoln", "GB"],
  ["University of Salerno", "IT"],
  ["University of Seoul", "KR"],
  ["University of Stavanger", "NO"],
  ["University of the Arts London", "GB"],
  ["University of the Sunshine Coast", "AU"],
  ["University of Ulsan", "KR"],
  ["University of Westminster", "GB"],
  ["University of Wroclaw", "PL"],
  ["V. N. Karazin Kharkiv National University", "UA"],
  ["Williams College", "US"],
  ["Xidian University", "CN"],
  ["Zurich University of Applied Sciences (ZHAW)", "CH"],
  ["Al-Quds University", "PS"],
  ["Altai State University", "RU"],
  ["Amity University", "IN"],
  ["Belarusian National Technical University (BNTU)", "BY"],
  ["Bina Nusantara University (BINUS)", "ID"],
  ["CY Cergy Paris University", "FR"],
  ["Dhofar University", "OM"],
  ["Effat University", "SA"],
  ["Escuela Superior Politécnica del Litoral (ESPOL)", "EC"],
  ["European University of Lefke", "CY"],
  ["Gachon University (Seoul, Korea)", "KR"],
  ["Instituto Politécnico Nacional (IPN)", "MX"],
  ["Kaohsiung Medical University", "TW"],
  ["Khon Kaen University", "TH"],
  ["Kyrgyz Russian Slavic University", "KG"],
  ["London South Bank University", "GB"],
  ["Louisiana State University", "US"],
  ["Middlesex University", "GB"],
  ["Nanjing Agricultural University", "CN"],
  ["Nanjing Normal University", "CN"],
  ["Nantes Université", "FR"],
  ["North South University", "BD"],
  ["Oklahoma State University", "US"],
  ["Osaka Metropolitan University", "JP"],
  ["Rhodes University", "ZA"],
  ["Tallinn University", "EE"],
  ["Universidad de los Andes - Chile", "CL"],
  ["Universidad de Oviedo", "ES"],
  ["Universidad del Rosario", "CO"],
  ["Universidad Espíritu Santo (UEES), Ecuador", "EC"],
  ["Universidad Europea", "ES"],
  ["Universidade Federal de Santa Catarina", "BR"],
  ["Universita' degli Studi di Ferrara", "IT"],
  ["Universitat Internacional de Catalunya", "ES"],
  ["Universität Rostock", "DE"],
  ["Université Paris-Est Créteil Val de Marne", "FR"],
  ["University of Beira Interior", "PT"],
  ["University of Brighton", "GB"],
  ["University of Calcutta", "IN"],
  ["UNIVERSITY OF GDAŃSK", "PL"],
  ["University of Kentucky", "US"],
  ["University of Maribor", "SI"],
  ["University of Mumbai", "IN"],
  ["University of Nizwa", "OM"],
  ["UPES", "IN"],
  ["Worcester Polytechnic Institute", "US"],
  ["Wroclaw University of Science and Technology (Wrocław Tech)", "PL"],
  ["Yarmouk University", "JO"],
  ["Yeshiva University", "US"],
  ["Addis Ababa University", "ET"],
  ["Aga Khan University", "PK"],
  ["Azerbaijan University of Architecture and Construction (AzUAC)", "AZ"],
  ["Banaras Hindu University", "IN"],
  ["Charles Sturt University", "AU"],
  ["Chungbuk National University", "KR"],
  ["Clark University", "US"],
  ["Clemson University", "US"],
  ["Future University in Egypt", "EG"],
  ["Gulf University for Science and Technology", "KW"],
  ["IMU University", "MY"],
  ["Jouf University", "SA"],
  ["Kanazawa University", "JP"],
  ["Macao Polytechnic University", "MO"],
  ["Mendel University in Brno", "CZ"],
  ["Nagasaki University", "JP"],
  ["NLC «Buketov Karaganda National Research University»", "KZ"],
  ["Philipps-Universität Marburg", "DE"],
  ["Politecnico di Bari", "IT"],
  ["Princess Sumaya University for Technology", "JO"],
  ["Rochester Institute of Technology (RIT)", "US"],
  ["Slovak University of Technology in Bratislava", "SK"],
  ["Sohar University", "OM"],
  ["Sophia University", "JP"],
  ["South Ural State University (National Research University)", "RU"],
  ["Southwest University", "CN"],
  ["Tokyo University of Agriculture and Technology", "JP"],
  ["Universidad Anáhuac México", "MX"],
  ["Universidad de Córdoba", "ES"],
  ["Universidad de Valladolid", "ES"],
  ["Universidad Nacional Mayor de San Marcos", "PE"],
  ["Universit degli Studi della Campania Luigi Vanvitelli", "IT"],
  ["Universitas Sebelas Maret (UNS)", "ID"],
  ["Université de Franche-Comté", "FR"],
  ["Université de Sherbrooke", "CA"],
  ["Université du Québec", "CA"],
  ["University at Albany SUNY", "US"],
  ["University Duesseldorf", "DE"],
  ["University of Alabama at Birmingham", "US"],
  ["University of Alaska Fairbanks", "US"],
  ["University of Bahrain", "BH"],
  ["University of Cyberjaya", "MY"],
  ["University of Peshawar", "PK"],
  ["University of Santo Tomas", "PH"],
  ["University of South Africa", "ZA"],
  ["Virginia Commonwealth University", "US"],
  ["Wuhan University of Technology", "CN"],
  ["Abylkas Saginov Karaganda Technical University", "KZ"],
  ["ADA University", "AZ"],
  ["Al Nahrain University", "IQ"],
  ["Al-Azhar University", "EG"],
  ["Aligarh Muslim University", "IN"],
  ["Almaty Technological University", "KZ"],
  ["An-Najah National University", "PS"],
  ["Anglia Ruskin University", "GB"],
  ["Arab Academy for Science, Technology and Maritime Transport (AASTMT)", "EG"],
  ["Asfendiyarov Kazakh National Medical University", "KZ"],
  ["Assiut University", "EG"],
  ["Athens University of Economics and Business", "GR"],
  ["Bahauddin Zakariya University", "PK"],
  ["Beijing University of Posts and Telecommunications", "CN"],
  ["Bergische Universität Wuppertal", "DE"],
  ["Bielefeld University", "DE"],
  ["Binghamton University SUNY", "US"],
  ["Birmingham City University", "GB"],
  ["BRAC University", "BD"],
  ["Carl von Ossietzky Universität Oldenburg", "DE"],
  ["CEU Universities", "ES"],
  ["Chitkara University", "IN"],
  ["City University of Macau", "MO"],
  ["Clarkson University", "US"],
  ["Cracow University of Technology (Politechnika Krakowska)", "PL"],
  ["D. Serikbayev East Kazakhstan Technical University", "KZ"],
  ["Daffodil International University", "BD"],
  ["Dankook University", "KR"],
  ["EGE UNIVERSITY", "TR"],
  ["Ernst-Moritz-Arndt-Universität Greifswald", "DE"],
  ["Ferdowsi University of Mashhad", "IR"],
  ["Financial University under the Government of the Russian Federation", "RU"],
  ["Fordham University", "US"],
  ["Gazi Üniversitesi", "TR"],
  ["George Mason University", "US"],
  ["Glasgow Caledonian University", "GB"],
  ["Guangdong University of Technology", "CN"],
  ["Guru Gobind Singh Indraprastha University", "IN"],
  ["Gyeongsang National University", "KR"],
  ["Hallym University", "KR"],
  ["Hanoi University of Science and Technology", "VN"],
  ["Harbin Engineering University", "CN"],
  ["Hohai University", "CN"],
  ["Hong Kong Shue Yan University", "HK"],
  ["Howard University", "US"],
  ["Huazhong Agricultural University", "CN"],
  ["Immanuel Kant Baltic Federal University", "RU"],
  ["Indian Institute of Technology Bhubaneswar", "IN"],
  ["Islamic University of Madinah", "SA"],
  ["Ivane Javakhishvili Tbilisi State University", "GE"],
  ["Kalinga Institute of Industrial Technology (KIIT) University", "IN"],
  ["Kangwon National University", "KR"],
  ["Kansas State University", "US"],
  ["King Mongkut's University of Technology Thonburi", "TH"],
  ["Kookmin University", "KR"],
  ["Kumamoto University", "JP"],
  ["Kyrgyz-Turkish Manas University", "KG"],
  ["Leeds Beckett University", "GB"],
  ["Lodz University of Technology", "PL"],
  ["London Metropolitan University", "GB"],
  ["Makerere University", "UG"],
  ["Mansoura University", "EG"],
  ["Marmara University", "TR"],
  ["MATE Hungarian University of Agriculture and Life Sciences", "HU"],
  ["Michigan Technological University", "US"],
  ["Middle East University Jordan", "JO"],
  ["Mississippi State University", "US"],
  ["Mustansiriyah University", "IQ"],
  ["Mutah University", "JO"],
  ["Mykolas Romeris University", "LT"],
  ["Narxoz University", "KZ"],
  ["National Chung Cheng University", "TW"],
  ["National Technical University Kharkiv Polytechnic Institute", "UA"],
  ["Nicolaus Copernicus University", "PL"],
  ["Niigata University", "JP"],
  ["Ningbo University", "CN"],
  ["North-West University", "ZA"],
  ["Northern Arizona University", "US"],
  ["Northern Borders University", "SA"],
  ["Northwest University (China)", "CN"],
  ["Obuda University", "HU"],
  ["Okayama University", "JP"],
  ["Panjab University, Chandigarh", "IN"],
  ["Pavol Jozef Šafárik University in Košice", "SK"],
  ["Pontificia Universidad Católica del Ecuador (PUCE)", "EC"],
  ["Pontifícia Universidade Católica de São Paulo", "BR"],
  ["Poznan University of Life Sciences", "PL"],
  ["Poznan University of Technology", "PL"],
  ["Prague University of Economics and Business", "CZ"],
  ["Riga Stradins University", "LV"],
  ["Ritsumeikan Asia Pacific University", "JP"],
  ["Robert Gordon University", "GB"],
  ["Roskilde University", "DK"],
  ["Saint Louis University", "US"],
  ["Samarkand State University", "UZ"],
  ["Seoul National University of Science and Technology", "KR"],
  ["Shaanxi Normal University", "CN"],
  ["Sheffield Hallam University", "GB"],
  ["Shiv Nadar University, Delhi NCR", "IN"],
  ["Siberian Federal University, SibFU", "RU"],
  ["Silesian University of Technology", "PL"],
  ["Soonchunhyang University", "KR"],
  ["Southern Federal University", "RU"],
  ["Southern Methodist University", "US"],
  ["SRM Institute of Science and Technology", "IN"],
  ["Sumgayit State University", "AZ"],
  ["Széchenyi István University (University of Győr)", "HU"],
  ["Tashkent State Technical University", "UZ"],
  ["Technical University of Kosice", "SK"],
  ["Technische Universität Chemnitz", "DE"],
  ["The Hashemite University", "JO"],
  ["The University of Alabama", "US"],
  ["The University of Lahore", "PK"],
  ["The University of Texas at Arlington", "US"],
  ["The University of Texas at San Antonio", "US"],
  ["Tokyo Metropolitan University", "JP"],
  ["Universidad Andrés Bello", "CL"],
  ["Universidad Argentina de la Empresa (UADE)", "AR"],
  ["Universidad Austral de Chile", "CL"],
  ["Universidad Autónoma Metropolitana (UAM)", "MX"],
  ["Universidad Católica Andres Bello", "VE"],
  ["Universidad de Belgrano (UB)", "AR"],
  ["Universidad de Cantabria", "ES"],
  ["Universidad de Castilla-La Mancha", "ES"],
  ["Universidad de Extremadura", "ES"],
  ["Universidad de Guadalajara (UDG)", "MX"],
  ["Universidad de La Sabana", "CO"],
  ["Universidad de las Américas Puebla (UDLAP)", "MX"],
  ["Universidad de León", "ES"],
  ["Universidad de Málaga", "ES"],
  ["Universidad de Puerto Rico", "PR"],
  ["Universidad de San Andrés - UdeSA", "AR"],
  ["Universidad EAFIT", "CO"],
  ["Universidad Externado de Colombia", "CO"],
  ["Universidad Nacional de Rosario (UNR)", "AR"],
  ["Universidad ORT Uruguay", "UY"],
  ["Universidad Peruana Cayetano Heredia (UPCH)", "PE"],
  ["Universidad Pontificia Bolivariana", "CO"],
  ["Universidad Rey Juan Carlos", "ES"],
  ["Universidad Simón Bolívar (USB)", "VE"],
  ["Universidad Técnica Federico Santa María (USM)", "CL"],
  ["Universidad Torcuato Di Tella", "AR"],
  ["Universidade Federal de São Carlos (UFSCar)", "BR"],
  ["Universidade Federal do Paraná - UFPR", "BR"],
  ["Universit de Bretagne Occidentale", "FR"],
  ["Universit degli Studi di Perugia", "IT"],
  ["Università degli Studi di Udine", "IT"],
  ["Universita' degli Studi \"G. d'Annunzio\" Chieti Pescara", "IT"],
  ["Universita' degli Studi dell'Aquila", "IT"],
  ["Universitas Sumatera Utara", "ID"],
  ["Universitat de Lleida (University of Lleida)", "ES"],
  ["Universitat Jaume I (CASTELLÓ)", "ES"],
  ["Université Lumière Lyon 2", "FR"],
  ["Université Mohammed V de Rabat", "MA"],
  ["Universiti Malaysia Perlis", "MY"],
  ["Universiti Malaysia Sabah (UMS)", "MY"],
  ["Universiti Malaysia Sarawak (UNIMAS)", "MY"],
  ["Universiti Tun Hussein Onn  Malaysia (UTHM)", "MY"],
  ["University of Agder", "NO"],
  ["University of Algarve", "PT"],
  ["University of Balamand", "LB"],
  ["University of Cassino and Southern Lazio", "IT"],
  ["University of Colombo", "LK"],
  ["University of Denver", "US"],
  ["University of Deusto", "ES"],
  ["University of East London", "GB"],
  ["University of Ha'il", "SA"],
  ["University of Ibadan", "NG"],
  ["University of Lagos", "NG"],
  ["University of Lancashire", "GB"],
  ["University of Lodz", "PL"],
  ["University of Louisville", "US"],
  ["University of Massachusetts Boston", "US"],
  ["University of Mississippi", "US"],
  ["University of Murcia", "ES"],
  ["University of Nairobi", "KE"],
  ["University of Naples Parthenope", "IT"],
  ["University of Nevada - Reno", "US"],
  ["University of North Texas", "US"],
  ["University of Pannonia", "HU"],
  ["University of Parma", "IT"],
  ["University of Regina", "CA"],
  ["University of Rhode Island", "US"],
  ["University of Roehampton, London", "GB"],
  ["University of Salento", "IT"],
  ["University of Salford", "GB"],
  ["University of Sfax", "TN"],
  ["University of South Bohemia in České Budějovice", "CZ"],
  ["University of Tabuk", "SA"],
  ["University of the Free State", "ZA"],
  ["University of the Western Cape", "ZA"],
  ["University of Vermont", "US"],
  ["University of Wolverhampton", "GB"],
  ["University of Wyoming", "US"],
  ["Van Lang University", "VN"],
  ["VSB - Technical University of Ostrava", "CZ"],
  ["West Virginia University", "US"],
  ["William & Mary", "US"],
  ["Xi'an Jiaotong Liverpool University", "CN"],
  ["Yerevan State University", "AM"],
  ["Yokohama City University", "JP"],
  ["Yokohama National University", "JP"],
  ["Yuan Ze University", "TW"],
  ["A'Sharqiyah University", "OM"],
  ["Adamson University", "PH"],
  ["Ahmadu Bello University, Zaria", "NG"],
  ["Al-Balqa Applied University", "JO"],
  ["Alexandru Ioan Cuza University", "RO"],
  ["Amman Arab University", "JO"],
  ["Amrita Vishwa Vidyapeetham", "IN"],
  ["Anhui University", "CN"],
  ["Ataturk University", "TR"],
  ["Azerbaijan State Pedagogical University", "AZ"],
  ["Baylor University", "US"],
  ["Beijing Foreign Studies University", "CN"],
  ["Beni-Suef University", "EG"],
  ["Brigham Young University", "US"],
  ["British University in Egypt", "EG"],
  ["Brock University", "CA"],
  ["Capital University – Egypt", "EG"],
  ["Central China Normal University", "CN"],
  ["Chung Yuan Christian University", "TW"],
  ["Damascus University", "SY"],
  ["Delta University for Science and Technology", "EG"],
  ["Democritus University of Thrace (DUTH)", "GR"],
  ["Dokuz Eylul Universitesi", "TR"],
  ["Empress Catherine II Saint Petersburg Mining University", "RU"],
  ["Erciyes University", "TR"],
  ["Estonian University of Life Sciences", "EE"],
  ["Florida Atlantic University - Boca Raton", "US"],
  ["Fu Jen Catholic University", "TW"],
  ["Fujian Normal University", "CN"],
  ["Galgotias University", "IN"],
  ["German University of Technology in Oman (GUtech)", "OM"],
  ["Gifu University", "JP"],
  ["Gunma University", "JP"],
  ["Henan University", "CN"],
  ["Ibn Tofail University", "MA"],
  ["Indian Institute of Information Technology, Allahabad", "IN"],
  ["Indiana University Indianapolis (IU Indianapolis)", "US"],
  ["Instituto Tecnológico de Buenos Aires (ITBA)", "AR"],
  ["International Christian University", "JP"],
  ["Islamic University of Lebanon", "LB"],
  ["Istanbul Aydin University", "TR"],
  ["ITESO, Universidad Jesuita de Guadalajara", "MX"],
  ["Ivan Franko National University of Lviv", "UA"],
  ["Izmir Institute of Technology (IZTECH)", "TR"],
  ["Jadara University", "JO"],
  ["Jeju National University", "KR"],
  ["Kagoshima University", "JP"],
  ["Kazakh-British Technical University", "KZ"],
  ["Kent State University", "US"],
  ["King Mongkuts Institute of Technology Ladkrabang (KMITL)", "TH"],
  ["Kwame Nkrumah University of Science and Technology", "GH"],
  ["Kyrgyz National University", "KG"],
  ["Kyushu Institute of Technology", "JP"],
  ["Lobachevsky University", "RU"],
  ["Loyola University Chicago", "US"],
  ["Lviv Polytechnic National University", "UA"],
  ["Malmo University", "SE"],
  ["Miami University", "US"],
  ["Nagoya Institute of Technology (NIT)", "JP"],
  ["National Research Saratov State University", "RU"],
  ["National Taipei University", "TW"],
  ["National Taiwan Ocean University", "TW"],
  ["National University of Kyiv-Mohyla Academy (NaUKMA)", "UA"],
  ["National University of Science and Technology POLITEHNICA Bucharest", "RO"],
  ["National University of Science and Technology, Oman", "OM"],
  ["New Mexico State University", "US"],
  ["Notre Dame University-Louaize NDU", "LB"],
  ["Odessa I.I.Mechnikov National University", "UA"],
  ["Ohio University", "US"],
  ["Oslo Metropolitan University", "NO"],
  ["Otto-Friedrich-Universität Bamberg", "DE"],
  ["Ozyegin University", "TR"],
  ["Palestine Technical University - Kadoorie", "PS"],
  ["Paul Valéry University Montpellier", "FR"],
  ["Portland State University", "US"],
  ["Pukyong National University", "KR"],
  ["Queen Margaret University , Edinburgh", "GB"],
  ["Riphah International University", "PK"],
  ["Russian Presidential Academy of National Economy and Public Administration", "RU"],
  ["Saint Petersburg Electrotechnical University ETU-LETI", "RU"],
  ["Saken Seifullin Kazakh Agrotechnical Research University", "KZ"],
  ["Samara National Research University (Samara University)", "RU"],
  ["San Diego State University", "US"],
  ["Sathyabama Institute of Science and Technology (Deemed to be University)", "IN"],
  ["Seattle University", "US"],
  ["Selcuk University", "TR"],
  ["Shanghai University of Finance and Economics", "CN"],
  ["Shinshu University", "JP"],
  ["Siksha ‘O’ Anusandhan (Deemed to be University), SOA", "IN"],
  ["Slovak University of Agriculture in Nitra", "SK"],
  ["Sookmyung Women's University", "KR"],
  ["Sumy State University", "UA"],
  ["Sungshin Women's University", "KR"],
  ["Taibah University", "SA"],
  ["Tamkang University", "TW"],
  ["Tashkent State Transport University", "UZ"],
  ["Tashkent State University of Economics", "UZ"],
  ["Technical University of Liberec", "CZ"],
  ["Tecnológico de Costa Rica -TEC", "CR"],
  ["Telkom University", "ID"],
  ["The Josip Juraj Strossmayer University of Osijek", "HR"],
  ["The University of Northampton", "GB"],
  ["The University of Notre Dame, Australia", "AU"],
  ["Tishk International University", "IQ"],
  ["Tokushima University", "JP"],
  ["Tomas Bata University in Zlin", "CZ"],
  ["Tunghai University", "TW"],
  ["UCAM Universidad Católica San Antonio de Murcia", "ES"],
  ["Universidad Autónoma Chapingo", "MX"],
  ["Universidad Autónoma de Nuevo León", "MX"],
  ["Universidad Autónoma del Estado de México (UAEMex)", "MX"],
  ["Universidad Central \"Marta Abreu\" de Las Villas", "CU"],
  ["Universidad Científica del Sur", "PE"],
  ["Universidad de Almeria", "ES"],
  ["Universidad de Cádiz", "ES"],
  ["Universidad de La Frontera (UFRO)", "CL"],
  ["Universidad de Las Américas (UDLA) Ecuador", "EC"],
  ["Universidad de Lima", "PE"],
  ["Universidad de Los Andes - (ULA) Mérida", "VE"],
  ["Universidad de Monterrey (UDEM)", "MX"],
  ["Universidad de Talca", "CL"],
  ["Universidad del Desarrollo (UDD)", "CL"],
  ["Universidad del Norte", "CO"],
  ["Universidad del Valle", "CO"],
  ["Universidad del Valle de Guatemala (UVG)", "GT"],
  ["Universidad Diego Portales", "CL"],
  ["Universidad ICESI", "CO"],
  ["Universidad Miguel Hernández de Elche", "ES"],
  ["Universidad Nacional de Asunción", "PY"],
  ["Universidad Nacional de Cuyo (UNCUYO)", "AR"],
  ["Universidad Nacional, Costa Rica", "CR"],
  ["Universidad Pablo de Olavide", "ES"],
  ["Universidade da Coruña", "ES"],
  ["Universidade do Estado do Rio de Janeiro (UERJ)", "BR"],
  ["Universidade Federal da Bahia", "BR"],
  ["Universidade Federal de Pernambuco (UFPE)", "BR"],
  ["Universidade Federal Fluminense", "BR"],
  ["Universita' degli Studi del Molise", "IT"],
  ["Universita' degli Studi di Sassari", "IT"],
  ["Universitas Muhammadiyah Yogyakarta (UMY)", "ID"],
  ["Universitat de les Illes Balears", "ES"],
  ["Universität Kassel", "DE"],
  ["Universität Paderborn", "DE"],
  ["Universität Siegen", "DE"],
  ["Universitatea de Vest din Timisoara /  West University of Timisoara", "RO"],
  ["Université Bourgogne Europe", "FR"],
  ["Université de Caen Normandie", "FR"],
  ["Université de Poitiers", "FR"],
  ["Université de Sousse", "TN"],
  ["Université Paris-Nanterre", "FR"],
  ["Université Polytechnique Hauts‑de‑France", "FR"],
  ["Université Sorbonne Paris Nord", "FR"],
  ["Université Toulouse - Jean Jaurès", "FR"],
  ["UNIVERSITI TEKNIKAL MALAYSIA MELAKA", "MY"],
  ["University of Anbar", "IQ"],
  ["University of Arkansas Fayetteville", "US"],
  ["University of Cagliari", "IT"],
  ["University of Dar es Salaam", "TZ"],
  ["University of Derby", "GB"],
  ["University of Evora", "PT"],
  ["University of Hradec Kralove", "CZ"],
  ["University of Idaho", "US"],
  ["University of Ioannina", "GR"],
  ["University of Isfahan", "IR"],
  ["University of Karachi", "PK"],
  ["University of Khartoum", "SD"],
  ["University of Management and Technology (UMT) Pakistan", "PK"],
  ["University of Memphis", "US"],
  ["University of Missouri, Kansas City", "US"],
  ["University of Neuchâtel", "CH"],
  ["University of Nevada - Las Vegas", "US"],
  ["University of New England Australia", "AU"],
  ["University of New Hampshire", "US"],
  ["University of Nigeria Nsukka", "NG"],
  ["University of North Carolina at Charlotte", "US"],
  ["University of Northern British Columbia", "CA"],
  ["University of Novi Sad", "RS"],
  ["University of Ostrava", "CZ"],
  ["University of Passau", "DE"],
  ["University of Peradeniya", "LK"],
  ["University of Primorska", "SI"],
  ["University of Rijeka", "HR"],
  ["University of San Francisco", "US"],
  ["University of Silesia in Katowice", "PL"],
  ["University of South Wales", "GB"],
  ["University of Split", "HR"],
  ["University of Texas El Paso", "US"],
  ["University of the Aegean", "GR"],
  ["University of Thessaly", "GR"],
  ["University of Toledo", "US"],
  ["University of Tunis", "TN"],
  ["University of Warmia and Mazury in Olsztyn", "PL"],
  ["University of Wisconsin Milwaukee", "US"],
  ["University of Zilina", "SK"],
  ["Utah State University", "US"],
  ["Warsaw University of Life Sciences  SGGW (WULS-SGGW)", "PL"],
  ["Western Michigan University", "US"],
  ["Zagazig University", "EG"],
  ["Zhejiang Sci-tech University", "CN"],
  ["Akdeniz Üniversitesi", "TR"],
  ["American International University-Bangladesh (AIUB)", "BD"],
  ["Bangladesh Agricultural University", "BD"],
  ["Beijing University of Chinese Medicine", "CN"],
  ["Benemerita Universidad Autonoma de Puebla", "MX"],
  ["Benha University - Egypt", "EG"],
  ["California Polytechnic State University", "US"],
  ["Can Tho University", "VN"],
  ["Canterbury Christ Church University", "GB"],
  ["China University of Political Science and Law", "CN"],
  ["Chittagong University of Engineering and Technology", "BD"],
  ["Cukurova University", "TR"],
  ["DePaul University", "US"],
  ["Doshisha University", "JP"],
  ["Escuela Politécnica Nacional", "EC"],
  ["Feng Chia University", "TW"],
  ["Georgian Technical University", "GE"],
  ["German University in Cairo", "EG"],
  ["Ho Chi Minh City University of Technology (HUTECH)", "VN"],
  ["Hongik University", "KR"],
  ["I. Razzakov Kyrgyz State Technical University", "KG"],
  ["Industrial University of Ho Chi Minh City (IUH)", "VN"],
  ["Instituto Tecnológico de Santo Domingo (INTEC)", "DO"],
  ["International Islamic University, Islamabad (IIU)", "PK"],
  ["Islamic Azad University", "IR"],
  ["Islamic University of Technology", "BD"],
  ["Jahangirnagar University", "BD"],
  ["Jamia Hamdard", "IN"],
  ["Karadeniz Technical University", "TR"],
  ["Kazakh Ablai Khan University of International Relations and World Languages", "KZ"],
  ["Khulna University of Engineering and Technology", "BD"],
  ["King Mongkut's University of Technology North Bangkok (KMUTNB)", "TH"],
  ["Kyoto Institute of Technology", "JP"],
  ["Lublin University of Technology", "PL"],
  ["Marquette University", "US"],
  ["Meiji University", "JP"],
  ["National Chinyi University of Technology", "TW"],
  ["National Dong Hwa University", "TW"],
  ["National Research University Moscow Power Engineering Institute (MPEI)", "RU"],
  ["Nelson Mandela University", "ZA"],
  ["Obafemi Awolowo University", "NG"],
  ["Pondicherry University", "IN"],
  ["Pontificia Universidad Católica Madre y Maestra (PUCMM)", "DO"],
  ["Pontifícia Universidade Católica do Rio Grande do Sul, PUCRS", "BR"],
  ["Sakarya University", "TR"],
  ["Shahjalal University of Science and Technology", "BD"],
  ["Shanghai International Studies University", "CN"],
  ["Shanghai Normal University", "CN"],
  ["Silpakorn University", "TH"],
  ["Stefan cel Mare University of Suceava", "RO"],
  ["Suranaree University of Technology", "TH"],
  ["Tanta University", "EG"],
  ["Technical University of Cluj-Napoca", "RO"],
  ["Technical University of Sofia", "BG"],
  ["The Islamia University of Bahawalpur,Pakistan", "PK"],
  ["The University of Georgia, Tbilisi", "GE"],
  ["Tokai University", "JP"],
  ["Toraighyrov University", "KZ"],
  ["Transilvania University of Brasov", "RO"],
  ["Universidad Autónoma de Guadalajara (UAG)", "MX"],
  ["Universidad Católica del Norte", "CL"],
  ["Universidad de La Laguna", "ES"],
  ["Universidad de San Carlos de Guatemala", "GT"],
  ["Universidad de Tarapaca", "CL"],
  ["Universidad de Valparaíso (UV)", "CL"],
  ["Universidad Nacional del Centro de la Provincia de Buenos Aires (UNICEN)", "AR"],
  ["Universidad Nacional del Litoral", "AR"],
  ["Universidad Peruana de Ciencias Aplicadas (UPC)", "PE"],
  ["Universidad Tecnológica Centroamericana (UNITEC)", "HN"],
  ["Universidad Tecnológica de Panamá (UTP)", "PA"],
  ["Universidad Tecnológica Nacional (UTN)", "AR"],
  ["Universidade Federal de Santa Maria", "BR"],
  ["Universidade Federal de Viçosa (UFV)", "BR"],
  ["Universidade Federal do Ceará (UFC)", "BR"],
  ["Universidade Presbiteriana Mackenzie", "BR"],
  ["Universitas Andalas", "ID"],
  ["Universitas Negeri Padang", "ID"],
  ["Universitas Negeri Yogyakarta", "ID"],
  ["Universitas Pendidikan Indonesia", "ID"],
  ["Universitas Trisakti (USAKTI)", "ID"],
  ["Universität Trier", "DE"],
  ["Université de Limoges", "FR"],
  ["Université de Rouen Normandie", "FR"],
  ["Universiti Kuala Lumpur (UniKL)", "MY"],
  ["Universiti Malaysia Kelantan", "MY"],
  ["University of Augsburg", "DE"],
  ["University of International Business and Economics", "CN"],
  ["University of Kaiserslautern-Landau (RPTU)", "DE"],
  ["University of Kerbala", "IQ"],
  ["University of Kufa", "IQ"],
  ["University of Miskolc", "HU"],
  ["University of Moratuwa", "LK"],
  ["University of Pardubice", "CZ"],
  ["University of Petra", "JO"],
  ["University of Rajshahi", "BD"],
  ["University of San Diego", "US"],
  ["University of Sarajevo", "BA"],
  ["University of Sri Jayawardenapura", "LK"],
  ["University of Tyumen", "RU"],
  ["Walailak University", "TH"],
  ["Yessenov University", "KZ"],
  ["Zarqa University (ZU)", "JO"],
  // ── Lebanon: full national coverage (universities, institutes, colleges) ──
  ["American University of Science and Technology (AUST)", "LB"],
  ["Antonine University (UA)", "LB"],
  ["Jinan University (Lebanon)", "LB"],
  ["Al-Kafaat University (AKU)", "LB"],
  ["Global University (Lebanon)", "LB"],
  ["Lebanese International University (LIU)", "LB"],
  ["American University of Technology (AUT Lebanon)", "LB"],
  ["Arts, Sciences and Technology University in Lebanon (AUL)", "LB"],
  ["Lebanese Canadian University (LCU)", "LB"],
  ["American University of Culture and Education (AUCE)", "LB"],
  ["Modern University for Business and Science (MUBS)", "LB"],
  ["University of Tripoli (Lebanon)", "LB"],
  ["Université La Sagesse (ULS)", "LB"],
  ["Rafik Hariri University (RHU)", "LB"],
  ["Lebanese German University (LGU)", "LB"],
  ["City University (Lebanon)", "LB"],
  ["Phoenicia University", "LB"],
  ["Al Maaref University", "LB"],
  ["AZM University", "LB"],
  ["Beirut International University", "LB"],
  ["Saint George University of Beirut (SGUB)", "LB"],
  ["Middle East University (Lebanon)", "LB"],
  ["Haigazian University", "LB"],
  ["ESA Business School (École Supérieure des Affaires)", "LB"],
  ["Imam Al-Ouzai College", "LB"],
  ["Sidon University Institute", "LB"],
  ["Jwaya University Institute of Technology", "LB"],
  ["Matn University Institute of Technology", "LB"],
  ["Al-Rassoul Al-Aazam University Institute for Health Sciences", "LB"],
  ["Lebanese Red Cross University Institute of Nursing", "LB"],
  ["Sisters of the Sacred Hearts University College of Technology", "LB"],
  ["Academic University College for Non-Violence and Human Rights (AUNOHR)", "LB"],
  ["Prince Sayyed Abdullah Al-Tanoukhi University College for Tawhid Sciences", "LB"],
  ["St. Paul Institute of Philosophy and Theology", "LB"],
  ["Near East School of Theology (NEST)", "LB"],
  ["Al-Daawa University Institute for Islamic Studies – Beirut", "LB"],
] as const;

/** Country codes present in the dataset, for the picker's filter. */
export const UNIVERSITY_COUNTRIES: readonly string[] = Array.from(
  new Set(UNIVERSITIES.map(([, country]) => country)),
).sort();
